### PR TITLE
Expect all techs output in ald benchmark (#235)

### LINKED ISSUE #235: `target_market_share` should output result for technologies that are not present in the loanbook
Sometimes there may be technologies present in the ALD, that are not present in the loanbook. These values should still be output for the `corporate economy`. 

I imagine these are being dropped by a `join` somewhere. In the following reprex, I would expect to see a value for `technology == "electric"` for the metric `corporate_economy`, with `production = 1` and `technology_share = 0.5`:

---

``` r
library(r2dii.data)
library(r2dii.analysis)

matched <- tibble::tribble(
  ~id_loan, ~loan_size_outstanding, ~loan_size_outstanding_currency, ~loan_size_credit_limit, ~loan_size_credit_limit_currency, ~id_2dii,            ~level, ~score,      ~sector,   ~name_ald,  ~sector_ald,
  "L162",                      1,                           "EUR",                       2,                            "EUR",    "UP1", "ultimate_parent",      1, "automotive", "company a", "automotive"
)

ald <- tibble::tribble(
  ~name_company,      ~sector, ~technology, ~year, ~production, ~emission_factor, ~plant_location, ~is_ultimate_owner,
  "company a", "automotive",       "ice",  2025,           1,                1,            "BF",               TRUE,
  "company b", "automotive",  "electric",  2025,           1,                1,            "BF",               TRUE
)

scenario <- tibble::tribble(
  ~scenario,      ~sector, ~technology,  ~region, ~year, ~tmsr, ~smsp, ~scenario_source,
  "sds", "automotive",       "ice", "global",  2025,   0.5, -0.08,      "demo_2020",
  "sds", "automotive",  "electric", "global",  2025,   0.5, -0.08,      "demo_2020"
)

target_market_share(
  matched, 
  ald, 
  scenario,
  region_isos_demo
)
#> # A tibble: 3 x 8
#>   sector technology  year region scenario_source metric production
#>   <chr>  <chr>      <dbl> <chr>  <chr>           <chr>       <dbl>
#> 1 autom… ice         2025 global demo_2020       proje…        1  
#> 2 autom… ice         2025 global demo_2020       corpo…        1  
#> 3 autom… ice         2025 global demo_2020       targe…        0.5
#> # … with 1 more variable: technology_share <dbl>
```

<sup>Created on 2020-11-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by jdhoffa**
Previously, a call to `left_join` caused some technologies to be dropped 
from the corporate economy benchmark value. Instead of calling to join, 
I now calculate the corporate_economy value at the end of 
`target_market_share`, and add it to the result using `rbind()`. 

Closes #235

### CODE REVIEW

**Comment by jdhoffa** [comment]
Also I updated all references to `region_isos_demo` -> `region_isos_stable`, which we missed in #230

**Review by maurolepore — APPROVED** [review]
LGTM

**Comment by maurolepore** [comment]
> Also I updated all references to region_isos_demo -> region_isos_stable, which we missed in #230

Sounds good. I noticed. Although I do prefer focused PRs, I know that sometimes the only way to keep the house clean is not to promise yourself to "clean tomorrow" but to just clean as you go.

**Pull request merged**
