### PR TITLE
bugfix sda multiple techs

### LINKED ISSUE #160: `projected` and `target_*` values for `steel` output of `target_sda()` seems off
From a conversation with a beta-tester:
> Something seems to be off with the steel projected and target output (very high)

sector | year | emission_factor_metric | emission_factor_value
-- | -- | -- | --
steel | 2019 | projected | 4.872001912
steel | 2019 | corporate_economy | 1.867306771
steel | 2019 | target_b2ds | 4.872001912
steel | 2019 | adjusted_scenario_b2ds | 1.867306771

> I checked the CO2 intensity values of matched companies and they are all less than 4:

year | min_value | max_value
-- | -- | -- 
2019 | 0.0236 | 3.02
2020 | 0.0236 | 3.02
2021 | 0.0236 | 3.02
2022 | 0.0236 | 3.02
2023 | 0.0236 | 3.02
2024 | 0.0236 | 3.02
2025 | 0.0236 | 3.02

---

I am unable to reproduce this error as of now, but will try again and post here as soon as I have.

### PR DESCRIPTION
**Pull request by jdhoffa**
The `ald` input is usually granular to the `technology` level, however for the SDA targets, we are calculating the average `emission_factors` at the sector level. 

That wasn't handled well in the `target_sda` function, causing very large `emission_factor` outputs when multiple technologies were present on input. 

This aggregation step at the beginning should solve that. 

Closes #160

### CODE REVIEW

**Comment by maurolepore** [comment]
Nice! 
I think it’s on draft mode but looks ready.

**Comment by jdhoffa** [comment]
Just switched it to draft mode on purpose, i fucked up and have to fix something! haha

**Comment by jdhoffa** [comment]
Didn't want it to get merged by accident

**Pull request merged**
