### PR TITLE
Plot percentage in units of "percent" (rather than a fraction)

### LINKED ISSUE #392: `percentage_of_initial_production_by_scope` outputs a fraction, and not a production
Notice in the reprex below, the difference between 125 and 120 is "-4%" and not "-0.04 percent". Thanks @MonikaFu 

``` r
library(tidyverse)
library(r2dii.data)
library(r2dii.analysis)

portfolio <- tibble::tribble(
  ~id_loan, ~loan_size_outstanding, ~loan_size_outstanding_currency, ~loan_size_credit_limit, ~loan_size_credit_limit_currency, ~id_2dii,            ~level, ~score,      ~sector, ~name_ald,  ~sector_ald,
  "L162",                      1,                           "EUR",                       2,                            "EUR",    "UP1", "ultimate_parent",      1, "automotive",   "comp1", "automotive",
  "L162",                      1,                           "EUR",                       2,                            "EUR",    "UP1", "ultimate_parent",      1, "automotive",   "comp2", "automotive"
)

ald <- tibble::tribble(
  ~name_company,      ~sector, ~technology, ~year, ~production, ~emission_factor, ~plant_location, ~is_ultimate_owner,
  "comp1", "automotive",  "electric",  2020,          10,                1,            "BF",               TRUE,
  "comp1", "automotive",       "ice",  2020,          30,                1,            "BF",               TRUE,
  "comp1", "automotive",  "electric",  2021,          20,                1,            "BF",               TRUE,
  "comp1", "automotive",       "ice",  2021,          20,                1,            "BF",               TRUE,
  "comp2", "automotive",  "electric",  2020,          90,                1,            "BF",               TRUE,
  "comp2", "automotive",       "ice",  2020,          95,                1,            "BF",               TRUE,
  "comp2", "automotive",  "electric",  2021,         100,                1,            "BF",               TRUE,
  "comp2", "automotive",       "ice",  2021,         100,                1,            "BF",               TRUE
)
scenario <- tibble::tribble(
  ~scenario,      ~sector, ~technology,  ~region, ~year, ~tmsr, ~smsp, ~scenario_source,
  "sds", "automotive",  "electric", "global",  2020,     1,     0,      "demo_2020",
  "sds", "automotive",       "ice", "global",  2020,     1,     0,      "demo_2020",
  "sds", "automotive",  "electric", "global",  2021,  1.85,  0.34,      "demo_2020",
  "sds", "automotive",       "ice", "global",  2021,   0.6,  -0.2,      "demo_2020"
)

out <- target_market_share(
  portfolio,
  ald,
  scenario,
  region_isos_demo,
  by_company = FALSE,
  weight_production = FALSE
)

out %>% 
  filter(technology == "ice", metric == "projected") %>% 
  select(year, production, percentage_of_initial_production_by_scope)
#> # A tibble: 2 × 3
#>    year production percentage_of_initial_production_by_scope
#>   <dbl>      <dbl>                                     <dbl>
#> 1  2020        125                                      0   
#> 2  2021        120                                     -0.04
```

<sup>Created on 2022-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by jdhoffa**
Closes #392 Thanks @MonikaFu

### CODE REVIEW

**Review by cjyetman — APPROVED** [review]
My only really comment here is that -0.04 is equal to -4%. TBH, I prefer the data to be the real value that it is, and if one wants to format that as a percentage, that's easy enough to do at the last moment. Multiplying the values *100 to put them in percentage units seems like a bad idea to me, but I suppose in this case that's what truly matches the column name, so I guess it's appropriate here.

**Comment by jdhoffa** [comment]
@cjyetman I tend to agree actually... this came from a conversation with @MonikaFu regarding what ends up getting plotted in `r2dii.plot` (and a desire to keep calculations, even very simple ones, out of that package). 

@MonikaFu what do you think?

**Comment by MonikaFu** [comment]
So - either we make it a fraction but then change the name or we rutn the numbers into 'percentages'.

**Comment by jdhoffa** [comment]
I feel like it's sort of ambiguous actually... like I personally wouldn't be surprised to see a column that is actually called `percent` and has units of percentage, but with values in the range (0,1)... It would almost surprise me more actually to see it have values in the range (0,100). Does that make sense?

**Comment by jdhoffa** [comment]
> @jdhoffa - you are right. Hmmm... I don't know to be honest. There is not a right answer I think. We just need to make a decision. On my end, I kind of don't like the idea of a plotting function called `plot_*` doing something else than that. But if we all think that it is better to multiply by 100 there then I'll do it and probably give a warning to the user that the function does it.
> 
> Alternatively, I could use `scales::percent` but also not 100% sure if I like this idea that the value that you are plotting is always a percentage as in theory, you might sometimes want to plot the absolute 'production' values.

So my preference would definitely be to output the percentages on the range (0,1) and handle percentage formatting in the plotting... Maybe something we can bring up n the dev hangout? but we need to make a decision soonish

**Comment by MonikaFu** [comment]
I will try to discuss this with @AlexAxthelm. Not opposed entirely to doing it in plotting but would like to consult with someone experienced before.

**Comment by MonikaFu** [comment]
@jdhoffa - the decision has been made to keep the column between 0 and 1. So I guess that you can close this PR?

**Comment by jdhoffa** [comment]
Closing!

**Pull request closed without merging**
