### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by maurolepore**
Render readme to reflect new outputs in long format.

### CODE REVIEW

**Comment by maurolepore** [comment]
This is a small change to syncronize README. Maybe I should try to setup the [GitHub Action to render README.md](https://github.com/r-lib/actions/blob/master/examples/render-readme.yaml). I tried it once and failed. But the file has been updated recently, and maybe the new versiono "just works".

**Comment by jdhoffa** [comment]
Do you want me to leave this open for now so you can see if we can automate this in an action?

**Comment by maurolepore** [comment]
Yeah, I'll try today.

**Comment by maurolepore** [comment]
I'll update redme in another pr.

**Pull request closed without merging**
